<?php

declare (strict_types=1);
namespace Aws\Cloud_Trail;

use Aws\S3\S3Client;
/**
 * The `Aws\CloudTrail\LogRecordIterator` provides an easy way to iterate over
 * log records from log files generated by AWS CloudTrail.
 *
 * CloudTrail log files contain data about your AWS API calls and are stored in
 * Amazon S3 at a predictable path based on a bucket name, a key prefix, an
 * account ID, a region, and date information. The files are gzipped and
 * contain structured data in JSON format. This class allows you to specify
 * options via its factory methods, including a date range, and emits each log
 * record from any log files that match the provided options.
 *
 * A log record containing data about an AWS API call is yielded for each
 * iteration on this object.
 */
class Log_Record_Iterator implements \Outer_Iterator
{
    private array $records;
    private int $record_index;
    public static function for_trail(S3Client $s3Client, Cloud_Trail_Client $cloud_trail_client, array $options = []): self
    {
        $log_file_iterator = Log_File_Iterator::for_trail($s3Client, $cloud_trail_client, $options);
        return new self(new Log_File_Reader($s3Client), $log_file_iterator);
    }
    /**
     * @param string   $s3BucketName
     *
     */
    public static function for_bucket(S3Client $s3Client, $s3bucket_name, array $options = []): self
    {
        $log_file_reader = new Log_File_Reader($s3Client);
        $iter = new Log_File_Iterator($s3Client, $s3bucket_name, $options);
        return new self($log_file_reader, $iter);
    }
    /**
     * @param string   $s3BucketName
     * @param string   $s3ObjectKey
     *
     */
    public static function for_file(S3Client $s3Client, $s3bucket_name, $s3object_key): self
    {
        $log_file_reader = new Log_File_Reader($s3Client);
        $log_file_iterator = new \ArrayIterator([['Bucket' => $s3bucket_name, 'Key' => $s3object_key]]);
        return new self($log_file_reader, $log_file_iterator);
    }
    public function __construct(private readonly Log_File_Reader $log_file_reader, private readonly \Iterator $log_file_iterator)
    {
        $this->records = [];
        $this->record_index = 0;
    }
    /**
     * Returns the current log record as an array.
     *
     * @return array|false
     */
    #[\Return_Type_Will_Change]
    public function current()
    {
        return $this->valid() ? $this->records[$this->record_index] : false;
    }
    #[\Return_Type_Will_Change]
    public function next(): void
    {
        $this->record_index++;
        // If all the records have been exhausted, get more records from the
        // next log file.
        while (!$this->valid()) {
            $this->log_file_iterator->next();
            $success = $this->load_records_from_current_log_file();
            if (!$success) {
                // The objects iterator is exhausted as well, so stop trying
                break;
            }
        }
    }
    #[\Return_Type_Will_Change]
    public function key()
    {
        if ($log_file = $this->log_file_iterator->current()) {
            return $log_file['Key'] . '.' . $this->record_index;
        }
        return null;
    }
    #[\Return_Type_Will_Change]
    public function valid()
    {
        return isset($this->records[$this->record_index]);
    }
    #[\Return_Type_Will_Change]
    public function rewind(): void
    {
        $this->log_file_iterator->rewind();
        $this->load_records_from_current_log_file();
    }
    #[\Return_Type_Will_Change]
    public function get_inner_iterator()
    {
        return $this->log_file_iterator;
    }
    /**
     * Examines the current file in the `logFileIterator` and attempts to read
     * it and load log records from it using the `logFileReader`. This method
     * expects that items pulled from the iterator will take the form:
     *
     *     [
     *         'Bucket' => '...',
     *         'Key'    => '...',
     *     ]
     *
     * @return bool Returns `true` if records were loaded and `false` if no
     *     records were found
     */
    private function load_records_from_current_log_file(): bool
    {
        $this->record_index = 0;
        $this->records = [];
        $log_file = $this->log_file_iterator->current();
        if ($log_file && isset($log_file['Bucket']) && isset($log_file['Key'])) {
            $this->records = $this->log_file_reader->read($log_file['Bucket'], $log_file['Key']);
        }
        return (bool) $log_file;
    }
}