<?php

declare (strict_types=1);
namespace Aws\Cloud_Trail;

use Aws\Cloud_Trail\Exception\Cloud_Trail_Exception;
use Aws\S3\S3Client;
/**
 * The `Aws\CloudTrail\LogFileIterator` provides an easy way to iterate over
 * log file generated by AWS CloudTrail.
 *
 * CloudTrail log files contain data about your AWS API calls and are stored in
 * Amazon S3 at a predictable path based on a bucket name, a key prefix, an
 * account ID, a region, and date information. This class allows you to specify
 * options, including a date range, and emits each log file that match the
 * provided options.
 *
 * Yields an array containing the Amazon S3 bucket and key of the log file.
 */
class Log_File_Iterator extends \Iterator_Iterator
{
    // For internal use
    public const DEFAULT_TRAIL_NAME = 'Default';
    public const PREFIX_TEMPLATE = 'prefix/AWSLogs/account/CloudTrail/region/date/';
    public const PREFIX_WILDCARD = '*';
    // Option names used internally or externally
    public const TRAIL_NAME = 'trail_name';
    public const KEY_PREFIX = 'key_prefix';
    public const START_DATE = 'start_date';
    public const END_DATE = 'end_date';
    public const ACCOUNT_ID = 'account_id';
    public const LOG_REGION = 'log_region';
    /**
     * Constructs a LogRecordIterator. This factory method is used if the name
     * of the S3 bucket containing your logs is not known. This factory method
     * uses a CloudTrail client and the trail name (or "Default") to find the
     * information about the trail necessary for constructing the
     * LogRecordIterator.
     *
     *
     * @return LogRecordIterator
     * @throws \InvalidArgumentException
     * @see LogRecordIterator::__contruct
     */
    public static function for_trail(S3Client $s3Client, Cloud_Trail_Client $cloud_trail_client, array $options = []): self
    {
        $trail_name = $options[self::TRAIL_NAME] ?? self::DEFAULT_TRAIL_NAME;
        $s3bucket_name = null;
        // Use the CloudTrail client to get information about the trail,
        // including the bucket name.
        try {
            $result = $cloud_trail_client->describe_trails(['trailNameList' => [$trail_name]]);
            $s3bucket_name = $result->search('trailList[0].S3BucketName');
            $options[self::KEY_PREFIX] = $result->search('trailList[0].S3KeyPrefix');
        } catch (Cloud_Trail_Exception $e) {
            // There was an error describing the trail
        }
        // If the bucket name is still unknown, then throw an exception
        if (!$s3bucket_name) {
            $prev = $e ?? null;
            throw new \InvalidArgumentException('The bucket name could not ' . 'be determined from the trail.', 0, $prev);
        }
        return new self($s3Client, $s3bucket_name, $options);
    }
    /**
     * Constructs a LogFileIterator using the specified options:
     *
     * - trail_name: The name of the trail that is generating our logs. If
     *   none is provided, then "Default" will be used, since that is the name
     *   of the trail created in the AWS Management Console.
     * - key_prefix: The S3 key prefix of your log files. This value will be
     *   overwritten when using the `fromTrail()` method. However, if you are
     *   using the constructor, then this value will be used.
     * - start_date: The timestamp of the beginning of date range of the log
     *   records you want to read. You can pass this in as a `DateTime` object,
     *   integer (unix timestamp), or a string compatible with `strtotime()`.
     * - end_date: The timestamp of the end of date range of the log records
     *   you want to read. You can pass this in as a `DateTime` object, integer
     *   (unix timestamp), or a string compatible with `strtotime()`.
     * - account_id: This is your AWS account ID, which is the 12-digit number
     *   found on the *Account Identifiers* section of the *AWS Security
     *   Credentials* page. See https://console.aws.amazon.com/iam/home?#security_credential
     * - log_region: Region of the services of the log records you want to read.
     *
     * @param string   $s3BucketName
     */
    public function __construct(private readonly S3Client $s3Client, private $s3bucket_name, array $options = [])
    {
        parent::__construct($this->build_list_objects_iterator($options));
    }
    /**
     * An override of the typical current behavior of \IteratorIterator to
     * format the output such that the bucket and key are returned in an array
     *
     * @return array|bool
     */
    #[\Return_Type_Will_Change]
    public function current()
    {
        if ($object = parent::current()) {
            return ['Bucket' => $this->s3bucket_name, 'Key' => $object['Key']];
        }
        return false;
    }
    /**
     * Constructs an S3 ListObjects iterator, optionally decorated with
     * FilterIterators, based on the provided options.
     *
     *
     * @return \Iterator
     */
    private function build_list_objects_iterator(array $options)
    {
        // Extract and normalize the date values from the options
        $start_date = isset($options[self::START_DATE]) ? $this->normalize_date_value($options[self::START_DATE]) : null;
        $end_date = isset($options[self::END_DATE]) ? $this->normalize_date_value($options[self::END_DATE]) : null;
        // Determine the parts of the key prefix of the log files being read
        $parts = ['prefix' => $options[self::KEY_PREFIX] ?? null, 'account' => $options[self::ACCOUNT_ID] ?? self::PREFIX_WILDCARD, 'region' => $options[self::LOG_REGION] ?? self::PREFIX_WILDCARD, 'date' => $this->determine_date_for_prefix($start_date, $end_date)];
        // Determine the longest key prefix that can be used to retrieve all
        // of the relevant log files.
        $candidate_prefix = ltrim(strtr(self::PREFIX_TEMPLATE, $parts), '/');
        $log_key_prefix = $candidate_prefix;
        $index = strpos($candidate_prefix, self::PREFIX_WILDCARD);
        if ($index !== false) {
            $log_key_prefix = substr($candidate_prefix, 0, $index);
        }
        // Create an iterator that will emit all of the objects matching the
        // key prefix.
        $objects_iterator = $this->s3Client->getIterator('ListObjects', ['Bucket' => $this->s3bucket_name, 'Prefix' => $log_key_prefix]);
        // Apply regex and/or date filters to the objects iterator to emit only
        // log files matching the options.
        $objects_iterator = $this->apply_regex_filter($objects_iterator, $log_key_prefix, $candidate_prefix);
        return $this->apply_date_filter($objects_iterator, $start_date, $end_date);
    }
    /**
     * Normalizes a date value to a unix timestamp
     *
     * @param int|string|\DateTimeInterface $date
     *
     * @return int
     * @throws \InvalidArgumentException if the value cannot be converted to
     *     a timestamp
     */
    private function normalize_date_value($date)
    {
        if (is_string($date)) {
            $date = strtotime($date);
        } elseif ($date instanceof \DateTimeInterface) {
            $date = $date->format('U');
        } elseif (!is_int($date)) {
            throw new \InvalidArgumentException('Date values must be a ' . 'string, an int, or a DateTime object.');
        }
        return $date;
    }
    /**
     * Uses the provided date values to determine the date portion of the prefix
     */
    private function determine_date_for_prefix($start_date, $end_date): string
    {
        // The default date value should look like "*/*/*" after joining
        $date_parts = array_fill_keys(['Y', 'm', 'd'], self::PREFIX_WILDCARD);
        // Narrow down the date by replacing the WILDCARDs with values if they
        // are the same for the start and end date.
        if ($start_date && $end_date) {
            foreach ($date_parts as $key => &$value) {
                $candidate_value = date($key, $start_date);
                if ($candidate_value === date($key, $end_date)) {
                    $value = $candidate_value;
                } else {
                    break;
                }
            }
        }
        return join('/', $date_parts);
    }
    /**
     * Applies a regex iterator filter that limits the ListObjects result set
     * based on the provided options.
     *
     * @param \Iterator $objectsIterator
     *
     * @return \Iterator
     */
    private function apply_regex_filter($objects_iterator, string $log_key_prefix, string $candidate_prefix)
    {
        // If the prefix and candidate prefix are not the same, then there were
        // WILDCARDs.
        if ($log_key_prefix !== $candidate_prefix) {
            // Turn the candidate prefix into a regex by trimming and
            // converting WILDCARDs to regex notation.
            $regex = rtrim($candidate_prefix, '/' . self::PREFIX_WILDCARD) . '/';
            $regex = strtr($regex, [self::PREFIX_WILDCARD => '[^/]+']);
            // After trimming WILDCARDs or the end, if the regex is the same as
            // the prefix, then no regex is needed.
            if ($log_key_prefix !== $regex) {
                // Apply a regex filter iterator to remove files that don't
                // match the provided options.
                $objects_iterator = new \Callback_Filter_Iterator($objects_iterator, fn($object) => preg_match("#{$regex}#", (string) $object['Key']));
            }
        }
        return $objects_iterator;
    }
    /**
     * Applies an iterator filter to restrict the ListObjects result set to the
     * specified date range.
     *
     * @param \Iterator $objectsIterator
     * @param int       $startDate
     * @param int       $endDate
     *
     * @return \Iterator
     */
    private function apply_date_filter($objects_iterator, $start_date, $end_date)
    {
        // If either a start or end date was provided, filter out dates that
        // don't match the date range.
        if ($start_date || $end_date) {
            $fn = function (array $object) use ($start_date, $end_date): bool {
                if (!preg_match('/[0-9]{8}T[0-9]{4}Z/', (string) $object['Key'], $m)) {
                    return false;
                }
                $date = strtotime($m[0]);
                return (!$start_date || $date >= $start_date) && (!$end_date || $date <= $end_date);
            };
            $objects_iterator = new \Callback_Filter_Iterator($objects_iterator, $fn);
        }
        return $objects_iterator;
    }
}